# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emissor',
            fields=[
                ('id_emissor', models.AutoField(primary_key=True, serialize=False)),
                ('id_agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencia_name', to='agencia.Agencia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
