# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moeda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Excursao',
            fields=[
                ('id_excursao', models.AutoField(primary_key=True, serialize=False)),
                ('excurcao_desc', models.CharField(max_length=45, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opcional',
            fields=[
                ('id_opcional', models.AutoField(primary_key=True, serialize=False)),
                ('opcional_desc', models.CharField(max_length=46, unique=True)),
                ('opcional_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_remessa', models.DecimalField(decimal_places=4, max_digits=6)),
                ('id_moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moeda.Moeda')),
            ],
        ),
    ]
