# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursao',
            fields=[
                ('id_excursao', models.AutoField(primary_key=True, serialize=False)),
                ('excurcao_desc', models.CharField(max_length=45, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
