# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
    ]
