# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0002_auto_20160829_1413'),
        ('excursao', '0002_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcional',
            fields=[
                ('id_opcional', models.AutoField(primary_key=True, serialize=False)),
                ('opcional_desc', models.CharField(max_length=46, unique=True)),
                ('opcional_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moeda.Moeda')),
            ],
        ),
    ]
