# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
