# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excursao', '0001_initial'),
        ('moeda', '0001_initial'),
        ('acomodacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id_pacote', models.AutoField(primary_key=True, serialize=False)),
                ('pacote_nome', models.CharField(max_length=45)),
                ('pacote_desc', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('pacote_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pacote_taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pacote_daybyday', models.TextField(blank=True, null=True)),
                ('pacote_obs', models.TextField(blank=True, null=True)),
                ('taxa_remessa', models.DecimalField(decimal_places=4, max_digits=6)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('id_excursao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursao_name', to='excursao.Excursao')),
                ('id_moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moeda_name', to='moeda.Moeda')),
            ],
        ),
        migrations.CreateModel(
            name='PacoteAcomadacao',
            fields=[
                ('id_pacote_acomodacao', models.AutoField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acomadacao_name', to='acomodacao.Acomodacao')),
                ('id_moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_acomodacao_moeda_name', to='moeda.Moeda')),
                ('id_pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_acomodacao_name', to='pacote.Pacote')),
            ],
        ),
        migrations.CreateModel(
            name='PacoteCidade',
            fields=[
                ('id_pacote_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_dias', models.IntegerField()),
                ('ordem', models.IntegerField()),
                ('id_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade_name', to='excursao.Cidade')),
                ('id_pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_cidade_name', to='pacote.Pacote')),
            ],
        ),
        migrations.CreateModel(
            name='PacoteOpcional',
            fields=[
                ('id_pacote_opcional', models.AutoField(primary_key=True, serialize=False)),
                ('id_opcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcional_name', to='excursao.Opcional')),
                ('id_pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_name', to='pacote.Pacote')),
            ],
        ),
    ]
