# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moeda', '0001_initial'),
        ('excursao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id_pacote', models.AutoField(primary_key=True, serialize=False)),
                ('pacote_nome', models.CharField(max_length=45)),
                ('pacote_desc', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('pacote_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pacote_taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pacote_daybyday', models.TextField()),
                ('pacote_obs', models.TextField()),
                ('id_excursao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursao_name', to='excursao.Excursao')),
                ('id_moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moeda_name', to='moeda.Moeda')),
            ],
        ),
    ]
