# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacote', '0002_auto_20170519_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacote',
            name='pacote_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
