# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='anexo',
            field=models.FileField(upload_to='default/documents'),
        ),
    ]
