# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('passageiro', '0001_initial'),
        ('emissor', '0001_initial'),
        ('excursao', '0001_initial'),
        ('pacote', '0001_initial'),
        ('acomodacao', '0001_initial'),
        ('moeda', '0001_initial'),
        ('escola', '0001_initial'),
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageiroOpcional',
            fields=[
                ('id_reserva_passageiro_opcional', models.AutoField(primary_key=True, serialize=False)),
                ('preco_reserva_opcional', models.DecimalField(decimal_places=2, max_digits=14)),
                ('id_moeda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moeda.Moeda')),
                ('id_opcional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='excursao.Opcional')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('id_agencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agencia.Agencia')),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Cliente')),
                ('id_emissor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emissor.Emissor')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaPassageiro',
            fields=[
                ('id_reserva_passageiro', models.AutoField(primary_key=True, serialize=False)),
                ('reserva_passageiro_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva_passageiro_cambio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reserva_passageiro_obs', models.CharField(max_length=200, null=True)),
                ('registro_interno', models.CharField(max_length=254, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('preco_acomodacao', models.DecimalField(decimal_places=2, max_digits=14)),
                ('id_acomodacao_pacote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acomodacao.Acomodacao')),
                ('id_escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Escola')),
                ('id_moeda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moeda.Moeda')),
                ('id_pacote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pacote.Pacote')),
                ('id_passageiro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='passageiro.Passageiro')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.Reserva')),
            ],
        ),
        migrations.CreateModel(
            name='StatusReserva',
            fields=[
                ('id_status_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StatusReservaPassageiro',
            fields=[
                ('id_status_reserva_passageiro', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='reservapassageiro',
            name='id_status_reserva_passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venda.StatusReservaPassageiro'),
        ),
        migrations.AddField(
            model_name='reservapassageiro',
            name='passageiro_opcional',
            field=models.ManyToManyField(to='venda.PassageiroOpcional'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_status_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venda.StatusReserva'),
        ),
        migrations.AddField(
            model_name='passageiroopcional',
            name='id_reserva_passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.ReservaPassageiro'),
        ),
    ]
