# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissor', '0001_initial'),
        ('agencia', '0002_agencia_logo'),
        ('cliente', '0006_auto_20160906_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('id_agencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agencia.Agencia')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Cliente')),
                ('id_emissor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emissor.Emissor')),
            ],
        ),
        migrations.CreateModel(
            name='StatusReserva',
            fields=[
                ('id_status_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StatusReservaPassageiro',
            fields=[
                ('id_status_reserva_passageiro', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_status_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venda.StatusReserva'),
        ),
    ]
