# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservapassageiro',
            name='id_acomodacao_pacote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acomodacao.Acomodacao'),
        ),
        migrations.AlterField(
            model_name='reservapassageiro',
            name='id_moeda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moeda.Moeda'),
        ),
        migrations.AlterField(
            model_name='reservapassageiro',
            name='id_pacote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pacote.Pacote'),
        ),
        migrations.AlterField(
            model_name='reservapassageiro',
            name='passageiro_opcional',
            field=models.ManyToManyField(null=True, to='venda.PassageiroOpcional'),
        ),
        migrations.AlterField(
            model_name='reservapassageiro',
            name='preco_acomodacao',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='reservapassageiro',
            name='reserva_passageiro_cambio',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reservapassageiro',
            name='reserva_passageiro_preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
