# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_auto_20170908_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='editou',
            field=models.BooleanField(default=False),
        ),
    ]
