# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id_moeda', models.AutoField(primary_key=True, serialize=False)),
                ('moeda_desc', models.CharField(max_length=15)),
                ('moeda_cambio', models.DecimalField(decimal_places=3, max_digits=4)),
                ('moeda_ultimaatualizacao', models.DateTimeField(auto_now_add=True)),
                ('moeda_simbolo', models.CharField(max_length=2)),
            ],
        ),
    ]
