# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tipo_pessoa',
            field=models.CharField(choices=[('Pessoa Fisíca', 'Pessoa Fisíca'), ('Pessoa Jurídica', 'Pessoa Jurídica')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
