# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_pessoa_tipo_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_pessoa',
            field=models.CharField(blank=True, choices=[('Pessoa Física', 'Pessoa Fisíca'), ('Pessoa Jurídica', 'Pessoa Jurídica')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa'),
        ),
    ]
