# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('dt_emissao_rg', models.DateTimeField(blank=True, null=True)),
                ('tempo_residencia', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_admissao', models.DateTimeField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=20, null=True)),
                ('principal_renda', models.CharField(blank=True, max_length=20, null=True)),
                ('outra_renda', models.CharField(blank=True, max_length=20, null=True)),
                ('patrimonio', models.CharField(blank=True, max_length=20, null=True)),
                ('banco', models.CharField(blank=True, max_length=20, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_banco', models.DateTimeField(blank=True, null=True)),
                ('telefone_banco', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
