# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default', '0001_initial'),
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pai', models.CharField(blank=True, max_length=45, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=45, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_dependentes', models.IntegerField(default=0)),
                ('tipo_residencia', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_emissao_rg', models.DateTimeField(blank=True, null=True)),
                ('tempo_residencia', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_admissao', models.DateTimeField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=20, null=True)),
                ('principal_renda', models.CharField(blank=True, max_length=20, null=True)),
                ('outra_renda', models.CharField(blank=True, max_length=20, null=True)),
                ('patrimonio', models.CharField(blank=True, max_length=20, null=True)),
                ('banco', models.CharField(blank=True, max_length=20, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('dt_banco', models.DateTimeField(blank=True, null=True)),
                ('telefone_banco', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj_empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('id_agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agencia.Agencia')),
                ('id_emissor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emissor.Emissor')),
                ('id_endereco_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.Endereco')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
