# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_id_endereco_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj_empresa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
