# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20160906_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_endereco_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.Endereco'),
        ),
    ]
