# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0001_initial'),
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id_passageiro', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField()),
                ('natularidade', models.CharField(blank=True, max_length=30, null=True)),
                ('observacao', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_passaporte', models.CharField(blank=True, max_length=10, null=True)),
                ('data_validade_passaporte', models.DateField(blank=True, null=True)),
                ('id_agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agencia.Agencia')),
                ('id_emissor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emissor.Emissor')),
                ('id_escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola_name', to='escola.Escola')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiro_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
