# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id_passageiro', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField()),
                ('natularidade', models.CharField(blank=True, max_length=30, null=True)),
                ('observacao', models.CharField(blank=True, max_length=250, null=True)),
                ('id_escola', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola_name', to='escola.Escola')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passageiro_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
