# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPublico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('pax', models.CharField(max_length=400)),
                ('grupo', models.CharField(max_length=400)),
                ('emissor', models.CharField(max_length=400)),
                ('agencia', models.CharField(max_length=400)),
                ('escola', models.CharField(max_length=400)),
                ('data_nascimento', models.DateField()),
                ('cel_pax', models.CharField(max_length=400)),
                ('email_pax', models.EmailField(blank=True, max_length=254, null=True)),
                ('resp_pax', models.CharField(max_length=400)),
                ('fone_resp', models.CharField(max_length=400)),
                ('email_resp', models.EmailField(blank=True, max_length=254, null=True)),
                ('cod_r1', models.IntegerField()),
                ('cod_r2', models.IntegerField()),
                ('cod_r3', models.IntegerField()),
                ('opcionais', models.CharField(max_length=400)),
                ('roomates', models.ManyToManyField(to='public_pax.PerfilPublico')),
            ],
        ),
    ]
