# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilpublico',
            name='roomates',
            field=models.ManyToManyField(related_name='_perfilpublico_roomates_+', to='public_pax.PerfilPublico'),
        ),
    ]
