# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pax', '0002_auto_20170615_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilpublico',
            name='roomates',
            field=models.ManyToManyField(blank=True, null=True, related_name='_perfilpublico_roomates_+', to='public_pax.PerfilPublico'),
        ),
    ]
