# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pax', '0008_auto_20170615_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilpublico',
            name='cel_pax',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
