# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pax', '0009_auto_20170615_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpublico',
            name='ficha_medica',
            field=models.FileField(blank=True, default='', null=True, upload_to='default/ficha_medica'),
        ),
    ]
