# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 15:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomodacao',
            name='numero',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acomodacao',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
