# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacao', '0003_auto_20160902_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomodacao',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
